x-logging: &loki-logging
  driver: local
  options:
    max-size: "50m"
    max-file: "10"

# x-logging: &loki-logging
#   driver: loki
#   options:
#     loki-url: "http://localhost:3100/loki/api/v1/push"
#     max-size: "50m"
#     max-file: "10"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    logging: *loki-logging

  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus/config.yaml
      - ./prometheus_data:/etc/prometheus/data
    command: -config.file=/etc/prometheus/config.yaml
    logging: *loki-logging

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro"
      - /sys:/host/sys:ro"
    logging: *loki-logging

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    logging: *loki-logging

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail/config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    logging: *loki-logging